export enum FeedTypes {
  CHANNEL_ONLINE = 'CHANNEL_ONLINE',
  REGISTER_CONFIRM_PHONE = 'REGISTER_CONFIRM_PHONE',
  REGISTER_CHANNEL = 'REGISTER_CHANNEL',

  SUCCESS_PREMIUM = 'SUCCESS_PREMIUM',
  CREATE_TEAM = 'CREATE_TEAM',
  PAYMENT_TICKETS = 'PAYMENT_TICKETS',
  REGISTER_CUP = 'REGISTER_CUP',
  CONFIRM_CUP = 'CONFIRM_CUP',
  NEW_MATCH = 'NEW_MATCH',

  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
  NEW_EVENT = 'NEW_EVENT',
}
